- name: Docker and Kubernetes installed
  hosts: all
  become: yes
  vars_files:
  - ../vars/main.yml



  tasks:
  - name: Download containerd.io deb package
    get_url:
      url={{ deb_package_url['container_io'] }} dest=/var/cache/apt/archives/containerd.io.deb force=no

  - name: Download docker-ce-cli deb package
    get_url:
      url={{ deb_package_url['docker_ce_cli'] }} dest=/var/cache/apt/archives/docker-ce-cli.deb force=no

  - name: Download docker-ce deb package
    get_url:
      url={{ deb_package_url['docker_ce'] }} dest=/var/cache/apt/archives/docker-ce.deb force=no

  - name: Install containerd.io deb package
    apt:
      deb: /var/cache/apt/archives/containerd.io.deb

  - name: Install docker-ce-cli deb package
    apt:
      deb: /var/cache/apt/archives/docker-ce-cli.deb

  - name: Install docker-ce deb package
    apt:
      deb: /var/cache/apt/archives/docker-ce.deb

  - name: Add ubuntu user to docker group
    user:
      name={{ ansible_user }} groups=docker
    register: task_result

  - name: Add the packages.cloud.google.com atp key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  
  - name: Add url to apt sources list
    shell: echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
    args:
      creates: /etc/apt/sources.list.d/kubernetes.list

  - name: apt update 
    apt:
      update_cache: no

  - name: Install libltdl7
    apt:
      name: 
      - libltdl7

  - name: Install kebelet, kubeadm and kubectl
    apt:
      name:
      - kubelet=1.18.5-00
      - kubeadm=1.18.5-00
      - kubectl=1.18.5-00

  - name: Reboot if these tasks were done for the first time
    shell: "sleep 3 && reboot"
    async: 1
    poll: 0
    when: task_result is changed 
  
  - name: Wait for reboot
    wait_for_connection:
      delay: 0
      timeout: 180
    when: task_result is changed 

  - name: Check Connection after rebooting
    ping:
    when: task_result is changed 
